version: '3'
services:
  django_web:
    build: .
    image: "django-es-kibana-logstash:latest"
    links:
      - logstash
      - es
    depends_on:
      - logstash
      - es
    ports:
      - "8000:8000"
    environment:
      LOGSTASH_HOST: logstash
      ELASTICSEARCH_URL: es:9200
  es:
    image: elasticsearch:5.6.10
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    ports:
      - "9200:9200"

  logstash:
    build: ./logstash
    image: "django-logstash:01"
    depends_on:
      - es
    links:
      - es
    ports:
      - "5959:5959"

  kibana:
    image: kibana:5.6.10
    links:
      - es
    depends_on:
      - es
    environment:
      ELASTICSEARCH_URL: http://es:9200
    ports:
      - "5601:5601"




