# Generated by Django 2.1 on 2018-08-27 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_web', '0002_auto_20180824_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='posted_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
